// QH_PHASE5A_ROUTE_LAB_ONLY
// Publication-safe planning data for the local supporting-route preproduction lab.

export const ROUTE_ORDER = [
  "for-industry",
  "for-startups",
  "industries",
  "proof",
  "maradin",
  "spark",
  "about",
  "contact",
  "404",
];

export const VIEWPORTS = [
  { id: "desktop", width: 1440, height: 900 },
  { id: "short-desktop", width: 1366, height: 650 },
  { id: "tablet-landscape", width: 1024, height: 768 },
  { id: "portrait", width: 768, height: 1024 },
  { id: "mobile", width: 390, height: 844 },
  { id: "mobile-narrow", width: 320, height: 800 },
  { id: "mobile-landscape", width: 844, height: 390 },
];

const sharedDependencies = ["semantic HTML", "shared Dark V2 tokens", "native document scroll"];

export const ROUTES = {
  "for-industry": {
    slug: "for-industry",
    publicPath: "/for-partners/",
    publicLabel: "For industry",
    eyebrow: "operating route 01",
    title: "Turn industrial needs into testable decisions.",
    purpose: "Frame a real industrial challenge, source relevant candidates and move toward bounded evidence.",
    audience: "Industrial challenge owners and operating stakeholders.",
    userQuestion: "How does an operational need become a responsible test and decision route?",
    overture: "A constrained industrial volume compresses around one challenge aperture.",
    chapters: ["Operational pressure", "Challenge definition", "Search field", "Candidate narrowing", "Test threshold", "Decision route"],
    arc: ["pressure", "definition", "search", "narrowing", "test", "decision"],
    signature: "Opposing graphite masses narrow into a sourcing corridor, cross a test gate and resolve as a decision plane.",
    motion: ["Focus", "Cross", "Resolve"],
    datum: "Ownership-and-criteria edge; visible only while the challenge is being bounded.",
    materials: ["compressed graphite", "scored steel", "warm neutral aperture", "restrained magenta test edge"],
    media: {
      essential: "No",
      repository: "No suitable governed route media is required.",
      drive: "No Drive review required for the strongest abstract thesis.",
      desired: "If later approved: one real industrial-context photograph with no unverified logos, people or facility implication.",
      risk: "A facility image can imply a client, partner or owned site.",
      fallback: "Authored architectural pressure field in CSS.",
    },
    publication: ["No partner or facility implication", "No metrics", "No service-brochure claims", "No overstated commercialisation"],
    conversion: "Route to the existing contact intent only; destination remains unverified.",
    reduced: "Static open aperture with the full chapter sequence in normal flow.",
    nojs: "Identical semantic order; all geometry is decorative and non-blocking.",
    mobile: "One vertical pressure boundary; masses release before text enters.",
    landscape: "Compressed overture with the aperture offset from the headline; no clipped copy.",
    performance: { runtime: "CSS geometry plus one input-driven RAF progress variable", js: "1.5–2.5 KB raw", css: "5–7 KB raw", media: "0 B", risk: "Low", dependency: "None" },
    risks: ["Drifting into a consultancy service page", "Making the corridor resemble a funnel", "Overusing the datum"],
    dependencies: [...sharedDependencies, "small optional route controller"],
    openQuestions: ["Approve abstract architecture over a later real facility image", "Confirm whether the existing closing action remains sufficiently qualified"],
    next: "for-startups",
  },
  "for-startups": {
    slug: "for-startups",
    publicPath: "/for-startups/",
    publicLabel: "For startups",
    eyebrow: "operating route 02",
    title: "Bring your technology into the real world.",
    purpose: "Show how a technology signal is tested for relevance, fit and field readiness without promising an outcome.",
    audience: "MVP+ technology teams seeking an industrial evidence route.",
    userQuestion: "What must align before a technology can credibly enter an industrial field test?",
    overture: "A small off-axis signal enters a much larger operating system.",
    chapters: ["Technology signal", "Readiness", "Relevance", "Industrial fit", "Field threshold", "Evidence"],
    arc: ["signal", "readiness", "relevance", "fit", "field", "evidence"],
    signature: "An exterior signal passes narrowing tolerance boundaries and aligns with one conditional field-access threshold.",
    motion: ["Conduct", "Focus", "Cross", "Resolve"],
    datum: "Alignment rail; present during fit, absent after field entry.",
    materials: ["fine conductive trace", "dark operating mass", "tolerance marks", "conditional warm field"],
    media: {
      essential: "No",
      repository: "No approved route media is needed.",
      drive: "No Drive review required.",
      desired: "If later approved: a precise technology detail, never a generic startup portrait.",
      risk: "Media can imply a customer, deployment or guaranteed access.",
      fallback: "CSS signal and tolerance architecture.",
    },
    publication: ["No guaranteed POC", "No guaranteed customer or investment", "No procurement or success implication", "Keep field access conditional"],
    conversion: "Existing startup contact intent; no invented destination.",
    reduced: "Static aligned corridor with every readiness condition visible.",
    nojs: "The signal begins aligned; content and navigation are complete.",
    mobile: "A vertical alignment corridor replaces diagonal travel.",
    landscape: "Signal and headline share a shallow field without fixed-height text.",
    performance: { runtime: "CSS geometry plus one input-driven RAF progress variable", js: "1.5–2.5 KB raw", css: "5–7 KB raw", media: "0 B", risk: "Low", dependency: "None" },
    risks: ["Reading as an accelerator promise", "Over-dramatising field access", "Signal motif becoming decorative repetition"],
    dependencies: [...sharedDependencies, "small optional route controller"],
    openQuestions: ["Approve the conditional threshold as the primary metaphor", "Confirm desired emphasis between SPARK and the general startup route"],
    next: "industries",
  },
  industries: {
    slug: "industries",
    publicPath: "/industries/",
    publicLabel: "Industries",
    eyebrow: "four operating territories",
    title: "Four contexts. Four material fields.",
    purpose: "Make the four approved domains spatially distinct before their headings are read.",
    audience: "Industry and technology visitors orienting to Quantum's approved scope.",
    userQuestion: "Which operating contexts are in scope, and how does each one feel materially different?",
    overture: "Four consecutive territories meet at one shared evidence seam.",
    chapters: ["Automotive & Mobility", "Logistics & Supply Chain", "Industry 4.0 / Advanced Manufacturing", "Energy & Infrastructure"],
    arc: ["low horizon", "transfer", "fixture", "load"],
    signature: "Native vertical travel changes the material field: velocity horizon, transfer stacks, rigid fixture, then structural span.",
    motion: ["Cross", "Release"],
    datum: "A local seam belongs to each territory; there is no universal decorative line.",
    materials: ["velocity glass", "stacked graphite", "machined fixture", "loaded infrastructural span"],
    media: {
      essential: "No",
      repository: "Existing repository media is not suitable for the four-domain system.",
      drive: "No Drive review required for the abstract territory thesis.",
      desired: "Only if later requested: four matched, governed documentary assets with equivalent visual weight.",
      risk: "Unmatched real imagery creates false facility, client and domain claims.",
      fallback: "Four authored CSS material territories.",
    },
    publication: ["Exactly four approved industries", "No defense or dual-use", "Technology categories are not extra industries", "No facility claims"],
    conversion: "Contextual route to For industry; no territory-specific lead machinery.",
    reduced: "Four complete static environments in sequence.",
    nojs: "All territories remain visible and readable in document order.",
    mobile: "Full-width stacked territories with simplified, non-overlapping geometry.",
    landscape: "Each territory uses a shallow distinct silhouette rather than a horizontal carousel.",
    performance: { runtime: "CSS territory states with current/adjacent enhancement only", js: "2.5–4 KB raw", css: "7–10 KB raw", media: "0 B", risk: "Medium compositing", dependency: "None" },
    risks: ["Regressing to four cards", "Excess compositing", "Territories becoming literal fake facilities"],
    dependencies: [...sharedDependencies, "small optional territory controller"],
    openQuestions: ["Approve the four abstract material vocabularies", "Choose whether headings enter before or after each material transition"],
    next: "proof",
  },
  proof: {
    slug: "proof",
    publicPath: "/pocs/",
    publicLabel: "Proof",
    eyebrow: "evidence archive / one record",
    title: "Evidence before scale.",
    purpose: "Treat one public proof as depth and confidence, not as an incomplete library.",
    audience: "Visitors evaluating how Quantum approaches evidence.",
    userQuestion: "What does a disciplined public proof record look like?",
    overture: "A vast quiet archive contains one exceptionally deep record aperture.",
    chapters: ["Evidence philosophy", "POC discipline", "Single public record", "Maradin aperture"],
    arc: ["quiet", "focus", "record", "entry"],
    signature: "One graphite record boundary opens into the governed Maradin poster and factual summary.",
    motion: ["Focus", "Cross"],
    datum: "Aperture edge; absent after the record opens.",
    materials: ["quiet archive void", "graphite record edge", "documentary light", "restrained evidence marker"],
    media: {
      essential: "Yes",
      repository: "The approved Maradin field-aperture poster is sufficient.",
      drive: "No Drive review required.",
      desired: "Existing approved 86 KB poster only.",
      risk: "Additional imagery could imply more public cases or hidden scale.",
      fallback: "Poster remains the only record image; text stays complete if it fails.",
    },
    publication: ["Exactly one public proof", "No anonymous or confidential placeholders", "No metrics", "No more-coming-soon filler"],
    conversion: "Open the Maradin record; secondary existing contact route remains qualified.",
    reduced: "The record is already open as a static aperture.",
    nojs: "Semantic record title, summary and link precede the governed image.",
    mobile: "The archive void shortens; the record occupies the full reading width.",
    landscape: "Record aperture and title share the first viewport without sticky media.",
    performance: { runtime: "CSS aperture; optional intersection class", js: "0–1.5 KB raw", css: "4–6 KB raw", media: "86 KB poster", risk: "Low", dependency: "None" },
    risks: ["Suggesting a larger hidden library", "Letting interface chrome dominate the record", "Poster crop weakening evidence"],
    dependencies: [...sharedDependencies, "approved Maradin poster"],
    openQuestions: ["Approve truthful scarcity as the principal visual stance", "Approve the poster crop at portrait widths"],
    next: "maradin",
  },
  maradin: {
    slug: "maradin",
    publicPath: "/pocs/maradin/",
    publicLabel: "Maradin",
    eyebrow: "field record 01",
    title: "Maradin — Dynamic Ground Projection",
    purpose: "Present the approved public record as documentary evidence with restrained editorial structure.",
    audience: "Visitors examining the conditions, sequence and evidence of the public POC.",
    userQuestion: "What happened in the field, under what conditions, and what was responsibly learned?",
    overture: "Documentary light establishes field reality before interface or explanation.",
    chapters: ["Challenge", "Technology", "Test design", "Execution", "Evidence", "Next step"],
    arc: ["reality", "conditions", "test", "observation", "evidence", "restraint"],
    signature: "In-flow documentary shutters reveal field records; captions remain peripheral and never cover evidence.",
    motion: ["Cross", "Resolve", "Release"],
    datum: "Occasional crop or caption edge; mostly absent.",
    materials: ["field-image grain", "matte editorial cut", "warm observation light", "quiet caption edge"],
    media: {
      essential: "Yes",
      repository: "The five approved Maradin assets are sufficient.",
      drive: "No Drive review required.",
      desired: "Existing approved poster, two stills and two user-controlled videos.",
      risk: "Visible field context can be mistaken for endorsement; no invented KPI or outcome.",
      fallback: "Complete chapter text plus approved still posters; videos remain user initiated.",
    },
    publication: ["Approved narrative fields only", "No commercial success or procurement claim", "No invented metrics", "Preserve qualified next-step wording"],
    conversion: "Return to Proof or continue to existing contact intent; no outcome claim.",
    reduced: "Composed approved stills; video only by explicit native control.",
    nojs: "Native controls, captions and the full chapter sequence remain available.",
    mobile: "Documentary frames become edge-to-edge in normal flow; captions follow images.",
    landscape: "One evidence frame and one concise chapter label share the shallow viewport.",
    performance: { runtime: "CSS shutters plus optional in-view class", js: "1–2 KB raw", css: "6–9 KB raw", media: "86 KB initial; 1.13 MB lazy stills; 8.10 MB user video", risk: "Low long-task / media-volume risk", dependency: "None" },
    risks: ["Documentary media buried under UI", "Two videos decoding together", "Field context read as endorsement", "EXIF orientation regression"],
    dependencies: [...sharedDependencies, "five existing governed Maradin assets", "native video controls"],
    openQuestions: ["Approve documentary shutters over bordered media panels", "Confirm whether visible field context needs an additional caption qualifier"],
    next: "spark",
  },
  spark: {
    slug: "spark",
    publicPath: "/spark/",
    publicLabel: "SPARK",
    eyebrow: "programme / closed threshold",
    title: "A runway from MVP+ to industrial POC.",
    purpose: "Explain the programme while making its closed status unmistakable and non-dead-end.",
    audience: "Technology teams evaluating the programme and its current status.",
    userQuestion: "What is the programme route, and what can I do while applications are closed?",
    overture: "A programme runway reaches a sealed threshold while institutional energy releases sideways into knowledge.",
    chapters: ["Programme proposition", "Eligibility", "Readiness route", "Applications closed", "Continued context"],
    arc: ["conduct", "prepare", "approach", "closed", "release"],
    signature: "The route resolves at a visibly sealed gate, then releases into programme knowledge and the general startup path.",
    motion: ["Conduct", "Resolve", "Release"],
    datum: "Runway edge terminating at the closed threshold.",
    materials: ["dormant conductive bed", "sealed warm threshold", "residual field glow", "side-release seam"],
    media: {
      essential: "No",
      repository: "No route media is needed.",
      drive: "No Drive review required.",
      desired: "None until a future approved programme cycle has governed documentary material.",
      risk: "Programme imagery could imply a current cohort, date or open application.",
      fallback: "CSS runway and closed material boundary.",
    },
    publication: ["Applications closed", "No waitlist or future date", "No cohort statistics", "No guaranteed POC"],
    conversion: "General startup route only; no application action.",
    reduced: "Static runway ending at an unequivocally closed gate, with content continuing below.",
    nojs: "Closed status appears before any programme detail and no control resembles an application action.",
    mobile: "Vertical runway; the closed plane is a normal section boundary.",
    landscape: "Shallow diagonal route stops before the status text, never behind it.",
    performance: { runtime: "CSS-only or optional in-view class", js: "0–1.5 KB raw", css: "4–6 KB raw", media: "0 B", risk: "Low", dependency: "None" },
    risks: ["A closed gate looking clickable", "Dead-end emotional tone", "Invented future-cycle language"],
    dependencies: [...sharedDependencies],
    openQuestions: ["Approve the sideways release as the non-application continuation", "Confirm preferred prominence of the closed status in the overture"],
    next: "about",
  },
  about: {
    slug: "about",
    publicPath: "/about/",
    publicLabel: "About",
    eyebrow: "the operating layer",
    title: "Built between industry and technology.",
    purpose: "Explain Quantum's operating position without inventing team, partner, history or scale surfaces.",
    audience: "Any visitor asking what Quantum is and where it operates.",
    userQuestion: "What is Quantum's role between industry needs and technology capability?",
    overture: "Two institutional masses are held apart by a narrow operating layer that belongs to neither side.",
    chapters: ["Purpose", "Industry-led model", "Operating position", "Herzliya context", "Working principles"],
    arc: ["separate", "hold", "connect", "locate", "resolve"],
    signature: "Interlocking section cuts reveal the between-position without becoming a network diagram, timeline or org chart.",
    motion: ["Focus", "Resolve"],
    datum: "Implied joint or tall editorial spine.",
    materials: ["institutional graphite", "narrow neutral joint", "interlocking cut", "quiet civic depth"],
    media: {
      essential: "No",
      repository: "No approved route media is required.",
      drive: "No Drive review required for the abstract thesis.",
      desired: "If later requested: one governed Herzliya/context image with explicit people, logo and location clearance.",
      risk: "Context imagery can imply facilities, team or institutional relationships.",
      fallback: "Interlocking CSS institutional masses.",
    },
    publication: ["No unverified team", "No partners or metrics", "No unsupported history", "No qFund roster crossover"],
    conversion: "Choice of existing industry/startup paths; no generic corporate funnel.",
    reduced: "Static interlocked planes with a visible operating layer.",
    nojs: "Complete institutional explanation in normal flow.",
    mobile: "The two masses stack with the operating layer visible as a central joint.",
    landscape: "Interlock shifts laterally while the H1 remains fully visible.",
    performance: { runtime: "CSS-only or optional in-view class", js: "0–1.5 KB raw", css: "4–6 KB raw", media: "0 B", risk: "Low", dependency: "None" },
    risks: ["Becoming a generic corporate timeline", "Implying team or partner scale", "Over-literal connection diagram"],
    dependencies: [...sharedDependencies],
    openQuestions: ["Approve the between-position as the only institutional metaphor", "Decide whether a future governed Herzliya image is desirable"],
    next: "contact",
  },
  contact: {
    slug: "contact",
    publicPath: "/contact/",
    publicLabel: "Contact",
    eyebrow: "three intent routes / endpoint pending",
    title: "Start with the challenge.",
    purpose: "Classify intent calmly without pretending an unverified contact destination exists.",
    audience: "Industry, technology and ecosystem/media visitors ready to choose a route.",
    userQuestion: "Which conversation am I trying to begin?",
    overture: "Three intent rails enter a calm arrival chamber and stop at one deliberately unresolved endpoint plane.",
    chapters: ["For industry", "For startups / technology", "General / ecosystem / media", "Verified endpoint pending"],
    arc: ["arrive", "identify", "focus", "stop"],
    signature: "URL hash and keyboard focus identify the selected intent; no JavaScript or simulated submission is needed.",
    motion: ["Focus", "Resolve"],
    datum: "Three intent rails terminate here rather than continuing decoratively.",
    materials: ["calm dark chamber", "three quiet rails", "focus aperture", "unresolved endpoint plane"],
    media: {
      essential: "No",
      repository: "No media needed.",
      drive: "Drive review is irrelevant.",
      desired: "None.",
      risk: "Decorative people or office imagery would create unsupported identity claims.",
      fallback: "CSS intent rails.",
    },
    publication: ["No form or backend", "No invented email or phone", "No response-time promise", "No submission simulation"],
    conversion: "Blocked pending a human-verified contact destination; intent classification only.",
    reduced: "Identical static chamber; focus is immediate and non-animated.",
    nojs: "CSS :target and native keyboard focus provide the complete behavior.",
    mobile: "Three large semantic intent sections stack with generous touch targets.",
    landscape: "Intent rails compress horizontally while labels remain in normal flow.",
    performance: { runtime: "CSS :target and native focus", js: "0 B", css: "2–4 KB raw", media: "0 B", risk: "None", dependency: "None" },
    risks: ["A pending endpoint looking actionable", "Lead-generation styling", "Inventing a direct contact detail"],
    dependencies: [...sharedDependencies, "human-verified contact destination before any conversion is enabled"],
    openQuestions: ["Provide and verify the real contact destination", "Approve whether the three intent labels need any wording adjustment"],
    next: "404",
  },
  "404": {
    slug: "404",
    publicPath: "/404/",
    publicLabel: "404",
    eyebrow: "signal absent",
    title: "The requested route is out of alignment.",
    purpose: "Provide a real semantic error state with quiet spatial dislocation and easy recovery.",
    audience: "Any visitor arriving at a missing URL.",
    userQuestion: "What happened, and how do I recover immediately?",
    overture: "One material plane and its alignment seam are quietly displaced from the rest of the system.",
    chapters: ["Missing route", "Recovery", "Global navigation"],
    arc: ["dislocate", "orient", "release"],
    signature: "Static spatial misregistration resolves visually toward the Home recovery link.",
    motion: ["Resolve", "Release"],
    datum: "Interrupted; never an active signal effect.",
    materials: ["displaced graphite plane", "broken alignment seam", "quiet negative space", "recovery focus"],
    media: {
      essential: "No",
      repository: "No media needed.",
      drive: "No Drive review required.",
      desired: "None.",
      risk: "Any cinematic media would weaken error semantics and performance.",
      fallback: "CSS misregistration.",
    },
    publication: ["Real HTTP 404", "noindex, follow", "No flippant joke", "Navigation and recovery remain complete"],
    conversion: "Home recovery plus global navigation.",
    reduced: "Identical static dislocation.",
    nojs: "Identical semantic error route.",
    mobile: "The displaced plane reduces so the recovery link stays in the first viewport.",
    landscape: "Minimal composition; navigation remains reachable without covering copy.",
    performance: { runtime: "CSS only", js: "0 B", css: "1–2 KB raw", media: "0 B", risk: "None", dependency: "None" },
    risks: ["Deployed route returning 200", "Recovery link losing focus visibility", "Tone becoming flippant"],
    dependencies: [...sharedDependencies, "static-host 404 response configuration"],
    openQuestions: ["Approve the revised non-joke line or retain the accepted current copy", "Confirm preferred recovery-link label"],
    next: "for-industry",
  },
};

export function routeForPath(pathname) {
  if (pathname === "/") return ROUTES["for-industry"];
  return Object.values(ROUTES).find((route) => route.publicPath === pathname) ?? null;
}

export function assertRouteData() {
  if (Object.keys(ROUTES).length !== 9 || ROUTE_ORDER.some((slug) => !ROUTES[slug])) {
    throw new Error("Phase 5A route lab must contain exactly the nine authorized routes");
  }
  const publicPaths = new Set(Object.values(ROUTES).map(({ publicPath }) => publicPath));
  if (publicPaths.size !== 9) throw new Error("Phase 5A route lab public-path projections must be unique");
  if (ROUTES.industries.chapters.length !== 4) throw new Error("Industries must contain exactly four territories");
  if (ROUTES.proof.media.repository.includes("sufficient") === false) throw new Error("Proof must bind its governed poster");
  if (!ROUTES.spark.publication.includes("Applications closed")) throw new Error("SPARK must remain closed");
}

assertRouteData();
